# .github/workflows/build-deploy.yml
name: Build and Deploy Presentations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build presentations
        run: npm run build
        env:
          # Add any needed environment variables
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: built-presentations
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Only deploy on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Download built presentations
        uses: actions/download-artifact@v4.1.8
        with:
          name: built-presentations
          path: docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./docs/dist
          # Optional: Add custom domain
          # cname: presentations.yourdomain.com
          